# Generated by Django 4.2.7 on 2023-12-12 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_job_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='stripe_card_last4',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='stripe_payment_method_id',
        ),
    ]
