# Generated by Django 4.2 on 2025-12-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_courier_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='job/photos/'),
        ),
    ]
