# Generated by Django 4.2 on 2025-12-07 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_alter_job_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('courier', 'Courier'), ('both', 'Both')], default='both', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('customer', 'Customer'), ('courier', 'Courier'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('is_quick_message', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.job')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaskedPhoneSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_masked_number', models.CharField(blank=True, max_length=20)),
                ('courier_masked_number', models.CharField(blank=True, max_length=20)),
                ('customer_real_number', models.CharField(blank=True, max_length=20)),
                ('courier_real_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='masked_session', to='core.job')),
            ],
        ),
    ]
