# Generated by Django 4.2 on 2025-12-07 02:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_quickmessage_message_maskedphonesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('boda_boda', 'Boda Boda (Motorcycle)'), ('tuk_tuk', 'TukTuk (Three-Wheeler)'), ('van', 'Van'), ('pickup', 'Pickup Truck'), ('car', 'Car')], default='boda_boda', max_length=20)),
                ('plate_number', models.CharField(max_length=20)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('max_weight_kg', models.FloatField(default=0)),
                ('cargo_length_cm', models.FloatField(default=0)),
                ('cargo_width_cm', models.FloatField(default=0)),
                ('cargo_height_cm', models.FloatField(default=0)),
                ('license_photo', models.ImageField(blank=True, null=True, upload_to='vehicle/license/')),
                ('insurance_photo', models.ImageField(blank=True, null=True, upload_to='vehicle/insurance/')),
                ('vehicle_photo', models.ImageField(blank=True, null=True, upload_to='vehicle/photos/')),
                ('helmet_cam_photo', models.ImageField(blank=True, null=True, upload_to='vehicle/helmet_cam/')),
                ('insurance_number', models.CharField(blank=True, max_length=100)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='courier',
            name='driving_license',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='courier',
            name='driving_license_photo',
            field=models.ImageField(blank=True, null=True, upload_to='courier/license/'),
        ),
        migrations.AddField(
            model_name='courier',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courier',
            name='national_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='courier',
            name='national_id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='courier/id/'),
        ),
        migrations.AddField(
            model_name='courier',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='courier/profile/'),
        ),
        migrations.AddField(
            model_name='courier',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='courier',
            name='total_deliveries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='vehicle_type',
            field=models.CharField(choices=[('boda_boda', 'Boda Boda (Motorcycle)'), ('tuk_tuk', 'TukTuk (Three-Wheeler)'), ('van', 'Van'), ('pickup', 'Pickup Truck'), ('car', 'Car')], default='boda_boda', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='weight',
            field=models.CharField(choices=[('light', 'Light (0-5 kg)'), ('medium', 'Medium (5-15 kg)'), ('heavy', 'Heavy (15-50 kg)'), ('very_heavy', 'Very Heavy (50+ kg)')], default='light', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='size',
            field=models.CharField(choices=[('small', 'Small (fits in hand)'), ('medium', 'Medium (fits in backpack)'), ('large', 'Large (needs carrier)'), ('extra_large', 'Extra Large (needs vehicle cargo)')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='courier',
            name='active_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_courier', to='core.vehicle'),
        ),
        migrations.AddField(
            model_name='courier',
            name='vehicles',
            field=models.ManyToManyField(blank=True, related_name='couriers', to='core.vehicle'),
        ),
        migrations.AddField(
            model_name='job',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.vehicle'),
        ),
    ]
