# Generated by Django 4.2 on 2025-12-07 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_bulkdeliveryitem_businesscredit_businessinvoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_name', models.CharField(max_length=255)),
                ('hub_type', models.CharField(choices=[('shop', 'Shop'), ('kiosk', 'Kiosk'), ('pharmacy', 'Pharmacy'), ('petrol_station', 'Petrol Station'), ('supermarket', 'Supermarket'), ('other', 'Other')], default='shop', max_length=20)),
                ('hub_code', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('opening_time', models.TimeField(default='08:00:00')),
                ('closing_time', models.TimeField(default='20:00:00')),
                ('operates_weekends', models.BooleanField(default=True)),
                ('storage_capacity', models.IntegerField(default=50)),
                ('current_occupancy', models.IntegerField(default=0)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('mpesa_number', models.CharField(max_length=20)),
                ('mpesa_name', models.CharField(max_length=255)),
                ('bank_account', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_ratings', models.IntegerField(default=0)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hubs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hubs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HubDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('pickup_code', models.CharField(max_length=8, unique=True)),
                ('status', models.CharField(choices=[('in_transit_to_hub', 'In Transit to Hub'), ('at_hub', 'At Hub'), ('ready_for_pickup', 'Ready for Pickup'), ('picked_up', 'Picked Up'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='in_transit_to_hub', max_length=30)),
                ('arrived_at_hub', models.DateTimeField(blank=True, null=True)),
                ('notified_recipient_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('is_cod', models.BooleanField(default=False)),
                ('cod_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cod_collected', models.BooleanField(default=False)),
                ('hub_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('commission_paid', models.BooleanField(default=False)),
                ('dropoff_photo', models.ImageField(blank=True, null=True, upload_to='hub_dropoffs/')),
                ('pickup_photo', models.ImageField(blank=True, null=True, upload_to='hub_pickups/')),
                ('special_instructions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.hub')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hub_delivery', to='core.job')),
            ],
            options={
                'verbose_name_plural': 'Hub Deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HubTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('commission', 'Commission Earned'), ('cod_collection', 'COD Collection'), ('payout', 'Payout'), ('adjustment', 'Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.CharField(max_length=255)),
                ('mpesa_transaction_id', models.CharField(blank=True, max_length=50)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50)),
                ('balance_before', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.hub')),
                ('hub_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hubdelivery')),
            ],
            options={
                'verbose_name_plural': 'Hub Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HubRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('review', models.TextField(blank=True)),
                ('service_quality', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('location_convenience', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('staff_friendliness', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='core.hubdelivery')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.hub')),
            ],
            options={
                'verbose_name_plural': 'Hub Ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HubPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_commissions', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_cod_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('net_payout', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('mpesa_transaction_id', models.CharField(blank=True, max_length=50)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='core.hub')),
            ],
            options={
                'verbose_name_plural': 'Hub Payouts',
                'ordering': ['-created_at'],
            },
        ),
    ]
